[2022-03-18 12:56:32,518] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_4 2022-03-17T00:00:00+00:00 [queued]>
[2022-03-18 12:56:32,539] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_4 2022-03-17T00:00:00+00:00 [queued]>
[2022-03-18 12:56:32,540] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-03-18 12:56:32,540] {taskinstance.py:1068} INFO - Starting attempt 2 of 2
[2022-03-18 12:56:32,542] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-03-18 12:56:32,573] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_4> on 2022-03-17T00:00:00+00:00
[2022-03-18 12:56:32,579] {standard_task_runner.py:52} INFO - Started process 20160 to run task
[2022-03-18 12:56:32,589] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_4', '2022-03-17T00:00:00+00:00', '--job-id', '9', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmpugxa2yvb', '--error-file', '/tmp/tmpb6kcf4wg']
[2022-03-18 12:56:32,594] {standard_task_runner.py:77} INFO - Job 9: Subtask task_4
[2022-03-18 12:56:32,809] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_4 2022-03-17T00:00:00+00:00 [running]> on host pc
[2022-03-18 12:56:33,053] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_4
AIRFLOW_CTX_EXECUTION_DATE=2022-03-17T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-17T00:00:00+00:00
[2022-03-18 12:56:33,054] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2022-03-18 12:56:33,059] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2022-03-18 12:56:33,084] {subprocess.py:75} INFO - Output:
[2022-03-18 12:56:36,090] {subprocess.py:83} INFO - Command exited with return code 0
[2022-03-18 12:56:36,216] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_4, execution_date=20220317T000000, start_date=20220318T072632, end_date=20220318T072636
[2022-03-18 12:56:36,281] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-03-18 12:56:36,291] {local_task_job.py:151} INFO - Task exited with return code 0
