[2022-03-18 13:48:16,807] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_1 2022-03-17T00:00:00+00:00 [queued]>
[2022-03-18 13:48:16,827] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_1 2022-03-17T00:00:00+00:00 [queued]>
[2022-03-18 13:48:16,828] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-03-18 13:48:16,828] {taskinstance.py:1068} INFO - Starting attempt 3 of 3
[2022-03-18 13:48:16,830] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-03-18 13:48:16,883] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_1> on 2022-03-17T00:00:00+00:00
[2022-03-18 13:48:16,889] {standard_task_runner.py:52} INFO - Started process 12029 to run task
[2022-03-18 13:48:16,897] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_1', '2022-03-17T00:00:00+00:00', '--job-id', '12', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmp97k99ndk', '--error-file', '/tmp/tmpdfra3tib']
[2022-03-18 13:48:16,898] {standard_task_runner.py:77} INFO - Job 12: Subtask task_1
[2022-03-18 13:48:17,003] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_1 2022-03-17T00:00:00+00:00 [running]> on host pc
[2022-03-18 13:48:17,143] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_1
AIRFLOW_CTX_EXECUTION_DATE=2022-03-17T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-17T00:00:00+00:00
[2022-03-18 13:48:17,144] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2022-03-18 13:48:17,145] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2022-03-18 13:48:17,157] {subprocess.py:75} INFO - Output:
[2022-03-18 13:48:20,160] {subprocess.py:83} INFO - Command exited with return code 0
[2022-03-18 13:48:20,237] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_1, execution_date=20220317T000000, start_date=20220318T081816, end_date=20220318T081820
[2022-03-18 13:48:20,326] {taskinstance.py:1245} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2022-03-18 13:48:20,369] {local_task_job.py:151} INFO - Task exited with return code 0
